{% set name = "Flask-SimpleLDAP" %}
{% set version = "2.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: d829f8163bae6d61d841707fa8a88bdcaae4862332c1acc13864b24ca82eaf25

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [py2k or win]

requirements:
  host:
    - pip
    - python
  run:
    - flask >=0.12.4
    - python
    - python-ldap >=3.0.0

test:
  imports:
    - flask_simpleldap

about:
  home: https://github.com/admiralobvious/flask-simpleldap
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "LDAP authentication extension for Flask"
  doc_url: http://flask-simpleldap.readthedocs.org/en/latest/

extra:
  recipe-maintainers:
    - tschoonj
